<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-15T14:19:35 IST" name="Suite" finished-at="2024-06-15T14:20:19 IST" duration-ms="43374">
    <groups>
      <group name="ErrorValidation">
        <method signature="ErrorValidationTest.LoginErrorValidation()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" name="LoginErrorValidation" class="selenium.tests.ErrorValidationTest"/>
        <method signature="ErrorValidationTest.ProductErrorValidation()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" name="ProductErrorValidation" class="selenium.tests.ErrorValidationTest"/>
      </group> <!-- ErrorValidation -->
    </groups>
    <test started-at="2024-06-15T14:19:35 IST" name="Error validation" finished-at="2024-06-15T14:20:19 IST" duration-ms="43374">
      <class name="selenium.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:35 IST" name="launchApplication" finished-at="2024-06-15T14:19:37 IST" duration-ms="2204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:37 IST" name="LoginErrorValidation" finished-at="2024-06-15T14:19:42 IST" duration-ms="4640" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Correct email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Correct email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at selenium.tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:42 IST" name="closeBrowser" finished-at="2024-06-15T14:19:46 IST" duration-ms="3577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:46 IST" name="launchApplication" finished-at="2024-06-15T14:19:47 IST" duration-ms="1668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:47 IST" name="LoginErrorValidation" finished-at="2024-06-15T14:19:51 IST" duration-ms="3587" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Correct email or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Correct email or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at selenium.tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:51 IST" name="closeBrowser" finished-at="2024-06-15T14:19:56 IST" duration-ms="5141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:56 IST" name="launchApplication" finished-at="2024-06-15T14:19:58 IST" duration-ms="1668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:19:58 IST" name="ProductErrorValidation" finished-at="2024-06-15T14:20:14 IST" duration-ms="16245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:selenium.tests.ErrorValidationTest@6cf0e0ba]" started-at="2024-06-15T14:20:14 IST" name="closeBrowser" finished-at="2024-06-15T14:20:19 IST" duration-ms="4569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- selenium.tests.ErrorValidationTest -->
    </test> <!-- Error validation -->
  </suite> <!-- Suite -->
</testng-results>
